### ISSUE TITLE
Support throwing error on dead files

### ISSUE THREAD

**Issue by RedHatter** [stauren/vite-plugin-deadfile#11]
I would like my CI to fail if there are any unused files. Could you add an option to throw an error or halt to build in some way when a dead file is detected?

**Comment by stauren** [comment]
OK, an option will be added in the next release.

**Comment by stauren** [comment]
`throwWhenFound` options is added in https://github.com/stauren/vite-plugin-deadfile/pull/12
 Please use v1.1.3+
