### ISSUE TITLE
outputDir must be inside: D:\workSpace\my-project\src, but got: D:\workSpace\my-project\src

### ISSUE THREAD

**Issue by AFine970** [stauren/vite-plugin-deadfile#16]
create new project

`yarn create vite my-vue-app --template vue-ts`

vite.config.ts
```js
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import deadFile from "vite-plugin-deadfile";

export default defineConfig({
  plugins: [
    vue(),
    deadFile({
      root: 'src',
      outputDir: "./",
      output: "dead-files.txt",
    })
  ],
});
```

error: outputDir must be inside: D:\workSpace\my-project\src, but got: D:\workSpace\my-project\src

This error is contradictory; it must be a bug.

**Comment by stauren** [comment]
It may be an issue with the Windows path separator, I will look into it.
Thanks for the feedback.

**Comment by anthonygore** [comment]
I got the same issue but on Mac:

outputDir must be inside: /Users/Workspace/ras-site/frontend/src, but got: /Users/Workspace/ras-site/frontend/src

**Comment by stauren** [comment]
@AFine970 @anthonygore Thanks for the feedback. Please try the version 1.2.3
