### ISSUE TITLE
Allow output to contain directory names etc.

### ISSUE THREAD

**Issue by TimonLukas** [stauren/vite-plugin-deadfile#9]
Hey there! Thanks for creating this plugin, really cool stuff :)

I just encountered a small annoyance - I'd like to have the `output` file appear in a subfolder of my project. This isn't possible right now since the plugin specifically only allows placing it in the root. Would it be possible to allow overwriting this? Maybe with a separate `outputDirectory` option or similar?

Thank you very much!

**Comment by stauren** [comment]
Sounds reasonable, I will add an `outputDir` options in the next version. Thanks for the feedback.

**Comment by stauren** [comment]
https://github.com/stauren/vite-plugin-deadfile/pull/10
Please use v1.1.2+, `outputDir` is configurable now.

**Comment by TimonLukas** [comment]
Awesome, thank you! And happy holidays :)
